/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.opdev.json;

import java.io.InputStream;

import jakarta.json.bind.Jsonb;
import jakarta.json.bind.JsonbBuilder;
import jakarta.json.bind.JsonbConfig;

import lombok.extern.log4j.Log4j2;
import tech.opdev.json.deserialization.DocumentAdapter;

@Log4j2
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        JsonbConfig config = new JsonbConfig().withAdapters(
            new DocumentAdapter()
        );
        Jsonb jsonb = JsonbBuilder.create(config);
        try (InputStream is = App.class.getResourceAsStream("/api.json")) {
            Document document = jsonb.fromJson(is, Document.class);
            log.info("Done!!! {}", document);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
